title: Site Name
author: Demian Ferreiro
# email: your-email@example.com
description: >-
  A blog i guess.
baseurl: ""
url: ""
rss: RSS
# show_excerpts: true
twitter_username: epidemian
github_username:  epidemian
mastodon:
  - username: epidemian
    instance: mastodon.social
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:categories/:title
collections:
  posts:
    permalink: /blog/:title
