title: Demian Ferreiro
email: your-email@example.com
description: >-
  My personal blog. Topics revolve around programming, and anything i find interesting.
baseurl: ""
url: ""
twitter_username: epidemian
github_username:  epidemian
mastodon:
  - username: epidemian
    instance: mastodon.social
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:categories/:title
collections:
  posts:
    permalink: /blog/:title
