title: Demian's blog
author: Demian Ferreiro
# email: your-email@example.com
# description: >-
#   Demian Ferreiro's personal blog
baseurl: ""
url: ""
rss: RSS
date_format: '%Y-%m-%d'
# show_excerpts: true
twitter_username: epidemian
github_username:  epidemian
mastodon:
  - username: epidemian
    instance: mastodon.social
plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /:categories/:title
collections:
  posts:
    permalink: /blog/:title

exclude:
  - CNAME
  - server
